export { default as Ecommerce } from './Ecommerce';
export { default as Orders } from './Orders';
export { default as Request } from './Request';
export { default as Schedule } from './Schedule';
export { default as Login } from './Login';
export { default as Error } from './Error';
export { default as Dashboard } from './Dashboard';
export { default as Service } from './Services';
export { default as AddService } from './AddService';
// export { default as AddEvent } from './AddEvent';
export { default as AddEvents } from './AddEvents';
export { default as UpdateEvent } from './UpdateEvent';
export { default as Work } from './Work';
export { default as ViewWork } from './ViewWork';
